#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json

from _studio_common import detect_active_genre, parse_preset_metadata, preset_path
from studio_core import (
    build_match_context,
    agent_public_title,
    expand_disciplines_for_checklists,
    infer_engine_from_text,
    keyword_matches_context,
    primary_engine_slug,
    related_research_refs,
    resolve_checklists,
    parse_agent_model_overrides,
    resolve_agent_model_profiles,
    starter_kit_summary,
)

ROUTES = [
    {
        "name": "agent system / operating model",
        "priority": 2,
        "keywords": [
            "multi-agent system",
            "operating model",
            "operating mode",
            "single-specialist default",
            "single specialist default",
            "controller title",
            "kaynexis",
            "command tree",
            "reporting lines",
            "async packets",
            "prompt journal",
            "review trail",
            "append-only",
        ],
        "discipline": "mastermind",
        "skills": ["intake-router", "feature-brief", "qa-matrix", "architecture-decision"],
        "agents": ["producer", "technical_director", "docs_researcher"],
        "docs": [
            "docs/reference/agent-system.md",
            "docs/examples/agent-system-example.md",
            "docs/research/game-development/foundations/agent-system.md",
            "docs/reference/mastermind-guide.md",
            "docs/reference/agent-portfolio.md",
            "docs/reference/agent-hierarchy.md",
            "docs/reference/prompt-journal.md",
            "docs/examples/mastermind-example.md",
        ],
        "extra_disciplines": ["agents", "hierarchy", "journal"],
        "validation_steps": [
            "Name the Kaynexis controller title, the specialist lanes, and the operating mode before implementation.",
            "Keep the user summary short and the role matrix explicit.",
            "Record the prompt history and agent journal trail if the task should be reviewable later.",
        ],
    },
    {
        "name": "capabilities / catalog / studio tour",
        "priority": 2,
        "keywords": [
            "capability",
            "capabilities",
            "capability catalog",
            "capability catalogs",
            "capability map",
            "capability maps",
            "capability index",
            "capability indexes",
            "what can you do",
            "what can this repo do",
            "what can this studio do",
            "what are you capable of",
            "what do you support",
            "studio capabilities",
            "repo capabilities",
            "full surface",
            "overview of capabilities",
            "capability overview",
            "intro",
            "tanıt",
            "tanitim",
            "tanıtım",
            "kabiliyet",
            "kabiliyetler",
            "kabiliyetlerimiz",
        ],
        "discipline": "capabilities",
        "skills": ["intake-router", "project-radar", "feature-brief"],
        "agents": ["producer", "docs_researcher", "mastermind"],
        "docs": [
            "docs/reference/capabilities.md",
            "docs/examples/capabilities-example.md",
            "docs/research/game-development/foundations/capabilities.md",
            "docs/README.md",
            "docs/reference/repo-tour.md",
            "docs/reference/task-prompt-examples.md",
            "docs/reference/workflow-recipes.md",
            "docs/examples/README.md",
            "docs/research/game-development/README.md",
            "docs/research/game-development/foundations/README.md",
            "studio/checklists/README.md",
            "studio/checklists/discipline/capabilities.toml",
            "studio/docs/active/eval-capabilities.md",
        ],
        "validation_steps": [
            "Name the major capability families before summarizing them.",
            "Keep the answer simple and the starter docs obvious.",
            "Keep the guide, example, research note, checklist, eval plan, and indexes synchronized.",
        ],
    },
    {
        "name": "agent validation / matrix catalog",
        "priority": 3,
        "keywords": [
            "validation matrix",
            "validation matrices",
            "agent validation",
            "agent readiness",
            "readiness matrix",
            "matrix catalog",
            "matrix pack",
            "validation pack",
            "proof matrix",
            "proof rows",
            "proof row",
            "lane readiness",
            "agent proof path",
            "single specialist mode",
            "operating model choice",
            "pair",
            "paired specialist",
            "panel",
            "transcript",
            "history",
            "model override",
            "lane model",
        ],
        "discipline": "agent_validation",
        "skills": ["intake-router", "qa-matrix", "feature-brief"],
        "agents": ["producer", "technical_director", "qa_lead", "docs_researcher"],
        "docs": [
            "docs/reference/agent-validation-matrix.md",
            "docs/examples/agent-validation-matrix-example.md",
            "docs/research/game-development/foundations/agent-validation-matrix.md",
            "docs/reference/agent-system.md",
            "docs/reference/agent-portfolio.md",
            "docs/reference/agent-hierarchy.md",
            "docs/reference/prompt-journal.md",
            "docs/reference/agent-transcript.md",
            "docs/reference/codex-model-guide.md",
            "docs/research/openai-codex-models.md",
            "docs/research/openai-codex-infra-findings.md",
            "studio/checklists/discipline/agent_validation.toml",
            "studio/docs/active/eval-agent-validation.md",
        ],
        "validation_steps": [
            "Name the operating mode, the validation matrix rows, and the proof path before implementation.",
            "Keep the single-specialist fallback visible even when the matrix fans out into a panel.",
            "Keep the guide, example, research note, checklist, and eval plan synchronized.",
        ],
    },
    {
        "name": "agent execution / work packet",
        "priority": 3,
        "keywords": [
            "agent execution",
            "work packet",
            "execution packet",
            "task packet",
            "agent packet",
            "packet template",
            "packet schema",
            "execution contract",
            "task envelope",
            "execution envelope",
            "custom rules",
            "stop conditions",
            "proof path",
        ],
        "discipline": "agent_execution",
        "skills": ["intake-router", "feature-brief", "qa-matrix", "architecture-decision"],
        "agents": ["producer", "technical_director", "qa_lead", "docs_researcher"],
        "docs": [
            "docs/reference/agent-execution.md",
            "docs/examples/agent-execution-example.md",
            "docs/research/game-development/foundations/agent-execution.md",
            "docs/reference/agent-system.md",
            "docs/reference/agent-portfolio.md",
            "docs/reference/agent-hierarchy.md",
            "docs/reference/prompt-journal.md",
            "docs/reference/agent-transcript.md",
            "docs/reference/custom-architecture.md",
            "docs/reference/feature-traceability.md",
            "docs/reference/handoff-contracts.md",
            "studio/checklists/discipline/agent_execution.toml",
            "studio/docs/active/agent-execution.md",
            "studio/docs/active/eval-agent-execution.md",
            "studio/docs/templates/agent-execution.md",
        ],
        "validation_steps": [
            "Name the owner, mode, goal, proof path, and custom rules before implementation.",
            "Keep the work packet separate from prompt history, transcript, and validation matrix.",
            "Keep the guide, example, research note, checklist, eval plan, and template synchronized.",
        ],
    },
    {
        "name": "speed pack / fast path",
        "priority": 6,
        "keywords": [
            "speed pack",
            "speedpack",
            "fast path",
            "fast lane",
            "fastest safe path",
            "shortest safe path",
            "fast bundle",
            "quick bundle",
            "rapid start",
            "smallest useful bundle",
            "urgent narrow task",
            "hız paketi",
            "hızlı iş",
            "hızlı başlat",
        ],
        "discipline": "speedpack",
        "skills": ["intake-router", "feature-brief", "qa-matrix"],
        "agents": ["producer", "technical_director", "docs_researcher", "qa_lead"],
        "docs": [
            "docs/reference/agent-speedpack.md",
            "docs/examples/agent-speedpack-example.md",
            "docs/research/game-development/foundations/agent-speedpack.md",
            "docs/setup/quick-access.md",
            "docs/reference/studio-map.md",
            "docs/reference/agent-system.md",
            "docs/reference/agent-execution.md",
            "studio/checklists/discipline/speedpack.toml",
            "studio/docs/active/eval-agent-speedpack.md",
        ],
        "validation_steps": [
            "Keep single specialist mode visible and the bundle as small as the task allows.",
            "Name the narrow route and one proof path before implementation.",
            "Add prompt history, transcript, or an execution packet only if later review is actually needed.",
        ],
    },
    {
        "name": "engine / tooling / packaging",
        "priority": 3,
        "keywords": [
            "starter kit",
            "starter-kit",
            "engine setup",
            "build pipeline",
            "artifact",
            "packaging",
            "package",
            "export",
            "batchmode",
            "buildcookrun",
            "uat",
            "asmdef",
            "manifest",
            "module",
            "plugin",
            "uproject",
        ],
        "discipline": "build-release",
        "skills": ["engine-setup", "build-pipeline", "tools-pipeline"],
        "agents": ["technical_director", "build_release_engineer", "engine_programmer"],
        "docs": ["studio/docs/active/engine-profile.md", "studio/docs/active/build-pipeline.md"],
        "validation_steps": ["Generate the exact engine command before implementation.", "Keep the command mirrored in docs and CI once it is real."],
    },
    {
        "name": "engine / evaluation / scorecard",
        "priority": 5,
        "keywords": [
            "engine eval",
            "engine evaluation",
            "engine scorecard",
            "engine comparison",
            "compare engines",
            "compare godot",
            "compare unity",
            "compare unreal",
            "build test performance",
            "build / test / performance",
            "toolchain readiness",
            "build smoke",
            "test smoke",
            "ci parity",
            "engine matrix",
            "engine decision",
            "engine choice",
            "readiness scorecard",
            "first blocker",
            "proof path",
            "scorecard",
        ],
        "discipline": "engine_eval",
        "skills": ["engine-setup", "build-pipeline", "qa-matrix", "perf-pass"],
        "agents": ["mastermind", "technical_director", "build_release_engineer", "qa_lead", "performance_analyst"],
        "docs": [
            "docs/reference/engine-eval.md",
            "docs/examples/engine-eval-example.md",
            "docs/research/game-development/foundations/engine-eval.md",
            "docs/reference/engine-selection-guide.md",
            "docs/reference/engine-map.md",
            "docs/reference/engine-examples.md",
            "docs/reference/benchmark-guide.md",
            "docs/reference/perf-guide.md",
            "docs/reference/quality-guide.md",
            "docs/reference/ci-cd.md",
            "studio/checklists/discipline/engine_eval.toml",
            "studio/docs/active/engine-eval.md",
            "studio/docs/active/eval-engine-eval.md",
        ],
        "validation_steps": [
            "Name the candidate engine families, build/test/performance/toolchain signals, and the first blocker before deciding.",
            "Keep the scorecard, active scorecard, and eval plan synchronized.",
            "Return one matrix or chart pack plus one repo implication.",
        ],
    },
    {
        "name": "engine / developer fit / recommendation",
        "priority": 6,
        "keywords": [
            "engine fit",
            "developer fit",
            "developer profile",
            "team fit",
            "team shape",
            "workflow appetite",
            "language comfort",
            "best engine for me",
            "which engine should i use",
            "which engine fits",
            "engine recommendation",
            "engine recommend",
            "recommend an engine",
            "recommend engine",
            "beginner",
            "beginner engine",
            "first engine",
            "new to engines",
            "solo dev",
            "solo developer",
            "solo maker",
            "one-person team",
            "small team",
            "new developer",
            "junior developer",
            "student",
            "designer-first",
            "tools-heavy",
            "blueprint-heavy",
            "c# team",
            "c++ team",
            "designer programmer",
            "visual scripting",
            "gdscript",
            "c# developer",
            "c++ developer",
            "hangi motor",
            "motor seçimi",
            "motor uyumu",
            "geliştirici uyumu",
            "ekip uyumu",
            "uygun motor",
        ],
        "discipline": "engine_fit",
        "skills": ["engine-setup", "feature-brief", "qa-matrix"],
        "agents": ["producer", "technical_director", "docs_researcher"],
        "docs": [
            "docs/reference/engine-fit.md",
            "docs/examples/engine-fit-example.md",
            "docs/research/game-development/foundations/engine-fit.md",
            "docs/reference/engine-selection-guide.md",
            "docs/reference/engine-map.md",
            "docs/reference/engine-examples.md",
            "docs/reference/engine-eval.md",
            "studio/checklists/discipline/engine_fit.toml",
            "studio/docs/active/engine-fit.md",
            "studio/docs/active/eval-engine-fit.md",
        ],
        "validation_steps": [
            "Name the developer profile and team shape before recommending an engine.",
            "Keep fit separate from engine-eval and name the first proof path only if the team wants one.",
            "Return one matrix or recommendation card plus one repo implication.",
        ],
    },
    {
        "name": "libraries / dependencies",
        "priority": 1,
        "keywords": [
            "library",
            "libraries",
            "dependency",
            "dependencies",
            "official library",
            "library set",
            "smallest official",
            "official stack",
            "official package",
            "official plugin",
            "package choice",
            "package selection",
            "dependency choice",
            "dependency selection",
            "plugin choice",
            "plugin selection",
            "sdk choice",
            "sdk selection",
            "sdk",
            "add-on",
            "addon",
            "addons",
            "plugin",
            "plugins",
            "module",
            "framework",
            "vendor",
            "third-party",
        ],
        "discipline": "library",
        "skills": ["engine-setup", "feature-brief", "qa-matrix"],
        "agents": ["technical_director", "engine_programmer", "producer"],
        "docs": ["docs/reference/library-guide.md", "docs/examples/library-example.md"],
        "validation_steps": [
            "Name the case and the smallest official stack before implementation.",
            "State the built-in option, the official package or plugin, and the fallback if no extra dependency is needed.",
        ],
    },
    {
        "name": "theory / design lenses",
        "priority": 2,
        "keywords": [
            "theory",
            "theory stack",
            "design theory",
            "design lens",
            "design lenses",
            "mda",
            "gameflow",
            "sdt",
            "pens",
            "affordance",
            "cognitive load",
            "game feel",
            "player motivation",
            "player fantasy",
            "challenge-skill",
            "challenge skill",
            "information hierarchy",
            "decision density",
            "theoretical framework",
            "theoretical",
            "lens order",
        ],
        "discipline": "theory",
        "skills": ["feature-brief", "mechanic-design", "qa-matrix"],
        "agents": ["game_designer", "technical_director", "docs_researcher"],
        "docs": [
            "docs/reference/theory-guide.md",
            "docs/examples/theory-example.md",
            "docs/research/game-development/foundations/theory.md",
            "docs/research/game-development/foundations/frameworks.md",
            "docs/research/game-development/foundations/ux.md",
            "docs/research/game-development/foundations/balance.md",
            "docs/research/game-development/foundations/quality.md",
            "studio/checklists/discipline/theory.toml",
            "studio/docs/active/eval-theory.md",
        ],
        "validation_steps": [
            "Name the player outcome and dominant tension before implementation.",
            "Choose the minimum lens stack and state what each lens is answering.",
            "Name one evidence source and one narrow proof path before expanding the slice.",
            "Keep the guide, example, research note, checklist, and eval plan synchronized.",
        ],
    },
    {
        "name": "architecture / systems design",
        "priority": 2,
        "keywords": [
            "architecture",
            "architectural",
            "system design",
            "state machine",
            "state graph",
            "phase graph",
            "event bus",
            "message bus",
            "signal architecture",
            "authority",
            "authoritative",
            "projection",
            "projection layer",
            "runtime truth",
            "canonical state",
            "replication",
            "prediction",
            "tick",
            "state ownership",
            "flow ownership",
        ],
        "discipline": "architecture",
        "skills": ["feature-brief", "qa-matrix", "architecture-decision"],
        "agents": ["technical_director", "lead_programmer", "docs_researcher"],
        "docs": [
            "docs/reference/architecture-guide.md",
            "docs/examples/architecture-example.md",
            "docs/research/game-development/architecture/README.md",
        ],
        "validation_steps": [
            "Name the canonical owner, the boundary, and the failure mode before implementation.",
            "Write down the state graph, event flow, or projection path if the task depends on one.",
        ],
    },
    {
        "name": "extensions / plugin packs",
        "priority": 3,
        "keywords": [
            "custom extension",
            "custom extensions",
            "extension pack",
            "extension packs",
            "plugin pack",
            "plugin packs",
            "hook pack",
            "hook packs",
            "optional module",
            "optional modules",
            "plugin-like add-on",
            "plugin like add on",
            "add-on",
            "add-ons",
            "add on",
            "add ons",
            "capability pack",
            "capability packs",
            "extension point",
            "extension points",
            "enable extension",
            "disable extension",
            "extension manifest",
            "plugin manifest",
            "pack manifest",
            "project-specific extension",
            "project specific extension",
        ],
        "discipline": "extensions",
        "skills": ["feature-brief", "architecture-decision", "tools-pipeline", "qa-matrix"],
        "agents": ["producer", "technical_director", "docs_researcher", "qa_lead"],
        "docs": [
            "docs/reference/extensions-guide.md",
            "docs/examples/extensions-example.md",
            "docs/research/game-development/foundations/extensions.md",
            "docs/reference/custom-architecture.md",
            "docs/reference/architecture-guide.md",
            "docs/reference/library-guide.md",
            "docs/reference/agent-system.md",
            "docs/reference/workflow-recipes.md",
            "studio/checklists/discipline/extensions.toml",
            "studio/extensions/README.md",
            "studio/extensions/custom/README.md",
            "studio/docs/active/eval-extensions.md",
        ],
        "validation_steps": [
            "Name the pack owner, the manifest fields, and whether the pack is opt-in or always-on before implementation.",
            "Write down the hook points, override points, and fallback path before the pack starts touching runtime or editor surfaces.",
            "Keep the guide, example, research note, checklist, extension README, and eval plan synchronized.",
        ],
    },
    {
        "name": "custom packs / feature registry",
        "priority": 4,
        "keywords": [
            "custom pack",
            "custom packs",
            "feature pack",
            "feature packs",
            "pack registry",
            "pack registries",
            "override manifest",
            "override manifests",
            "house-rule pack",
            "house-rule packs",
            "project-specific feature",
            "project specific feature",
            "custom feature",
            "custom features",
        ],
        "discipline": "custom_packs",
        "skills": ["feature-brief", "architecture-decision", "tools-pipeline", "qa-matrix"],
        "agents": ["producer", "technical_director", "docs_researcher", "qa_lead"],
        "docs": [
            "docs/reference/custom-packs.md",
            "docs/examples/custom-packs-example.md",
            "docs/research/game-development/foundations/custom-packs.md",
            "docs/reference/custom-architecture.md",
            "docs/reference/extensions-guide.md",
            "docs/reference/architecture-guide.md",
            "docs/reference/library-guide.md",
            "docs/reference/agent-system.md",
            "docs/reference/workflow-recipes.md",
            "docs/reference/task-prompt-examples.md",
            "studio/checklists/discipline/custom_packs.toml",
            "studio/docs/active/custom-packs-adr.md",
            "studio/docs/active/eval-custom-packs.md",
            "studio/docs/templates/custom-packs.md",
        ],
        "validation_steps": [
            "Name the pack type, the canonical owner, and whether the pack is opt-in or always-on before implementation.",
            "Write down the fixed rules, overrideable rules, hook points, override points, and fallback path.",
            "Keep the guide, example, research note, checklist, ADR, and eval plan synchronized.",
        ],
    },
    {
        "name": "custom / architecture / rules",
        "priority": 3,
        "keywords": [
            "custom architecture",
            "custom architecture process",
            "custom rule",
            "custom rules",
            "custom request",
            "custom requests",
            "request contract",
            "rule pack",
            "rule packs",
            "override contract",
            "project-specific architecture",
            "project specific architecture",
            "project-specific rule",
            "project specific rule",
            "bespoke architecture",
            "house rule",
            "house rules",
            "override point",
            "override points",
        ],
        "discipline": "custom",
        "skills": ["feature-brief", "architecture-decision", "qa-matrix"],
        "agents": ["producer", "technical_director", "docs_researcher", "qa_lead"],
        "docs": [
            "docs/reference/custom-architecture.md",
            "docs/examples/custom-architecture-example.md",
            "docs/research/game-development/foundations/custom-architecture.md",
            "docs/reference/architecture-guide.md",
            "docs/reference/agent-system.md",
            "docs/reference/workflow-recipes.md",
            "docs/reference/task-prompt-examples.md",
            "studio/checklists/discipline/custom.toml",
            "studio/docs/active/eval-custom-architecture.md",
        ],
        "validation_steps": [
            "Name what is fixed, what is overrideable, and who owns each part before implementation.",
            "Write down rule precedence, request contract terms, and the fallback when custom rules do not apply.",
            "Keep the custom guide, example, checklist, and eval plan synchronized.",
        ],
    },
    {
        "name": "agent orchestration / master mind",
        "priority": 2,
        "keywords": [
            "mastermind",
            "master mind",
            "orchestration",
            "orchestrator",
            "broad orchestration",
            "broad task",
            "broad request",
            "cross-functional",
            "cross functional",
            "multi-step",
            "multi step",
            "simple user summary",
            "simple user summaries",
            "simple user output",
            "internal worker handoff",
            "internal worker handoffs",
            "worker handoff",
            "worker handoffs",
            "supervisor agent",
            "planner-executor",
            "planner executor",
            "multi-agent",
            "agent management",
            "control loop",
            "control plan",
            "worker handoff",
            "delegation plan",
            "delegate",
            "delegation",
            "specialist work",
        ],
        "discipline": "mastermind",
        "skills": ["intake-router", "feature-brief", "qa-matrix"],
        "agents": ["producer", "technical_director", "docs_researcher"],
        "docs": [
            "docs/reference/agent-system.md",
            "docs/examples/agent-system-example.md",
            "docs/reference/mastermind-guide.md",
            "docs/examples/mastermind-example.md",
            "docs/research/game-development/foundations/mastermind.md",
        ],
        "validation_steps": [
            "Keep the user-facing summary simple before any worker detail.",
            "Name the specialist roles, evidence, and validation path before delegating.",
        ],
    },
    {
        "name": "openai / codex / agent platform",
        "priority": 4,
        "keywords": [
            "openai",
            "codex",
            "codex cloud",
            "codex cli",
            "codex compatibility",
            "agents sdk",
            "agent builder",
            "chatkit",
            "background mode",
            "shell tool",
            "tool shell",
            "prompt policy",
            "prompt version",
            "prompt versions",
            "tool approvals",
            "tool approval",
            "internet access",
            "eval path",
            "trace grading",
            "developer message",
            "system message",
            "messages object",
            "docs mcp",
            "agent platform",
            "prompt steering",
            "prompt routing",
            "traceable eval",
            "traceable evaluations",
            "agent workflow",
            "controller policy",
            "single specialist default",
        ],
        "discipline": "mastermind",
        "skills": ["intake-router", "feature-brief", "qa-matrix", "architecture-decision"],
        "agents": ["producer", "technical_director", "docs_researcher"],
        "docs": [
            "docs/research/openai-codex-infra-findings.md",
            "docs/reference/codex-compatibility.md",
            "docs/reference/codex-model-guide.md",
            "docs/examples/codex-model-guide-example.md",
            "docs/research/openai-codex-models.md",
            "docs/reference/agent-system.md",
            "docs/examples/agent-system-example.md",
            "docs/reference/mastermind-guide.md",
            "docs/examples/mastermind-example.md",
            "docs/reference/agent-portfolio.md",
            "docs/reference/agent-hierarchy.md",
            "docs/reference/prompt-journal.md",
            "docs/reference/quality-process.md",
            "docs/reference/benchmark-guide.md",
            "docs/reference/eval-strategy.md",
            "docs/reference/workflow-recipes.md",
            "docs/reference/task-prompt-examples.md",
            "studio/docs/active/eval-openai-codex.md",
        ],
        "extra_disciplines": ["openai_codex"],
        "validation_steps": [
            "Start with the OpenAI/Codex research note and the compatibility contract before splitting work.",
            "Keep controller policy stable and task-specific prompt details separate.",
            "Name the prompt version, eval path, and tool-access assumptions before implementation.",
            "If the task is about model choice, name the model and plan tier separately from the routing decision.",
            "Keep single-specialist mode visible even if the internal workflow fans out.",
        ],
    },
    {
        "name": "openai / codex / model selection",
        "priority": 5,
        "keywords": [
            "model selection",
            "model guide",
            "model matrix",
            "which model should i use",
            "which openai model should i use",
            "plan tier",
            "subscription tier",
            "rate limits",
            "developer mode",
            "gpt-5.4",
            "gpt-5.4 pro",
            "gpt-5.4-pro",
            "gpt-5.4 mini",
            "gpt-5.4-mini",
            "gpt-5.4 nano",
            "gpt-5.4-nano",
            "chatgpt plus",
            "chatgpt pro",
            "chatgpt business",
            "chatgpt enterprise",
            "chatgpt education",
            "codex app",
        ],
        "discipline": "openai_models",
        "skills": ["intake-router", "feature-brief", "qa-matrix", "architecture-decision"],
        "agents": ["producer", "technical_director", "docs_researcher"],
        "docs": [
            "docs/research/openai-codex-models.md",
            "docs/reference/codex-model-guide.md",
            "docs/examples/codex-model-guide-example.md",
            "docs/research/openai-codex-infra-findings.md",
            "docs/reference/codex-compatibility.md",
            "docs/reference/agent-system.md",
            "docs/reference/mastermind-guide.md",
            "docs/reference/agent-portfolio.md",
            "docs/reference/agent-hierarchy.md",
            "docs/reference/prompt-journal.md",
            "docs/reference/quality-process.md",
            "docs/reference/benchmark-guide.md",
            "docs/reference/eval-strategy.md",
            "studio/docs/active/eval-openai-models.md",
        ],
        "extra_disciplines": ["openai_codex"],
        "validation_steps": [
            "Name the surface first: ChatGPT/Codex app or API.",
            "Name the selected model and why it beats the smaller or larger alternatives.",
            "Name the plan tier only when the task is about ChatGPT/Codex app access or developer mode.",
            "Keep the smallest-model-that-fits rule visible in the final answer.",
        ],
    },
    {
        "name": "steam / market intelligence",
        "priority": 5,
        "keywords": [
            "steam intel",
            "steam intelligence",
            "steam market intelligence",
            "steam stats",
            "steam statistics",
            "steam signals",
            "steam market",
            "steam store",
            "steam store traffic",
            "steam-first",
            "steam-first survival",
            "steam-first survival game",
            "steamworks",
            "store and platform traffic reporting",
            "traffic reporting",
            "store traffic",
            "store page traffic",
            "utm analytics",
            "wishlist reporting",
            "wishlists",
            "steam wishlists",
            "steam community discussions",
            "steam discussions",
            "community hub",
            "forum signals",
            "forum themes",
            "discussion threads",
            "review sentiment",
            "steam hardware survey",
            "hardware mix",
            "steam deck verified",
            "steam deck",
        ],
        "discipline": "steam_intel",
        "skills": ["data-telemetry", "community-ops", "project-radar"],
        "agents": ["mastermind", "producer", "community_manager", "analytics_engineer", "art_director"],
        "docs": [
            "docs/reference/steam-intel.md",
            "docs/examples/steam-intel-example.md",
            "docs/research/game-development/production/steam-intel.md",
            "docs/reference/sector-intel.md",
            "docs/reference/marketing-guide.md",
            "docs/reference/repo-tour.md",
            "docs/reference/agent-guide.md",
            "docs/reference/workflow-recipes.md",
            "docs/reference/task-prompt-examples.md",
            "docs/research/game-development/production/README.md",
            "studio/docs/active/eval-steam-intel.md",
        ],
        "extra_disciplines": ["steam_intel"],
        "validation_steps": [
            "Name the Steam source family and the current time window before summarizing.",
            "Separate store traffic, wishlists, forum themes, hardware mix, and market context.",
            "Return one simple chart pack or dashboard schema plus one repo implication.",
        ],
    },
    {
        "name": "platform / compatibility / readiness",
        "priority": 6,
        "keywords": [
            "platform compatibility",
            "platform readiness",
            "compatibility matrix",
            "readiness matrix",
            "support tier",
            "support tiers",
            "release sequence",
            "release sequencing",
            "cross-platform",
            "multi-platform",
            "core family",
            "supported family",
            "demo-only",
            "research-only",
            "deferred",
            "family split",
            "platform delta",
            "platform targets",
            "windows",
            "macos",
            "linux",
            "steam deck",
            "steam os",
            "steamworks",
            "proton",
            "web",
            "browser",
            "web demo",
            "pwa",
            "android",
            "ios",
            "mobile",
            "webos",
            "android tv",
            "google tv",
            "television",
            "tv",
            "10-foot",
            "focus navigation",
            "controller parity",
            "suspend resume",
            "touch layout",
            "store review",
        ],
        "discipline": "platform_compatibility",
        "skills": ["porting-plan", "web-build-readiness", "mobile-optimization", "build-pipeline", "qa-matrix"],
        "agents": ["mastermind", "porting_engineer", "performance_analyst", "ux_designer", "build_release_engineer", "certification_manager"],
        "docs": [
        "docs/reference/platform-guide.md",
        "docs/reference/cross-platform-guide.md",
        "docs/examples/platform-example.md",
        "docs/examples/cross-platform-example.md",
        "docs/research/game-development/production/platform-compatibility.md",
        "docs/research/game-development/production/cross-platform.md",
        "docs/research/game-development/production/platform.md",
        "docs/research/game-development/production/README.md",
        "docs/reference/sector-intel.md",
            "docs/examples/sector-intel-example.md",
            "studio/docs/active/platform-targets.md",
            "studio/docs/active/eval-platform-compatibility.md",
            "docs/reference/workflow-recipes.md",
            "docs/reference/task-prompt-examples.md",
        ],
        "extra_disciplines": ["platform_compatibility"],
        "validation_steps": [
            "Name the source family and the current target family before summarizing.",
            "Separate input, performance, policy, store or distribution, support tier, and display or UX deltas.",
            "Return one matrix or chart pack plus one repo or release-sequence implication.",
            "Keep the guide, example, research note, active target doc, checklist, and eval plan synchronized.",
        ],
    },
    {
        "name": "agent hierarchy / command tree",
        "priority": 2,
        "keywords": [
            "hierarchy",
            "command tree",
            "command-tree",
            "chain of command",
            "reporting line",
            "reporting lines",
            "report up",
            "reporting up",
            "org chart",
            "org-chart",
            "status packet",
            "status packets",
            "async lane",
            "async lanes",
            "asynchronous",
            "public title",
            "titles",
            "software architect",
            "quality controller",
            "creator lead",
            "release captain",
            "director tier",
            "lead tier",
            "specialist tier",
            "validator tier",
        ],
        "discipline": "hierarchy",
        "skills": ["intake-router", "feature-brief", "qa-matrix", "architecture-decision"],
        "agents": ["producer", "technical_director", "qa_lead"],
        "docs": [
            "docs/reference/agent-hierarchy.md",
            "docs/examples/agent-hierarchy-example.md",
            "docs/research/game-development/foundations/agent-hierarchy.md",
            "docs/reference/mastermind-guide.md",
        ],
        "validation_steps": [
            "Name the controller tier, the public title for each lane, and the parent tier before implementation.",
            "Keep single specialist mode visible if the task is actually narrow.",
        ],
    },
    {
        "name": "agent portfolio / role matrix",
        "priority": 2,
        "keywords": [
            "agent portfolio",
            "role matrix",
            "role map",
            "role catalog",
            "agent roster",
            "single specialist",
            "paired specialist",
            "multi agent",
            "multi-agent",
            "specialist lane",
            "specialist panel",
            "controller",
            "supervisor",
            "orchestration",
            "delegate",
            "delegation",
        ],
        "discipline": "agents",
        "skills": ["intake-router", "feature-brief", "qa-matrix"],
        "agents": ["producer", "technical_director", "docs_researcher"],
        "docs": [
            "docs/reference/agent-portfolio.md",
            "docs/examples/agent-portfolio-example.md",
            "docs/research/game-development/foundations/agent-portfolio.md",
            "docs/reference/mastermind-guide.md",
        ],
        "validation_steps": [
            "Name the controller, the specialist lanes, and the operating mode before implementation.",
            "Keep the user summary short and the role matrix explicit.",
        ],
    },
    {
        "name": "genre / plan schema",
        "priority": 3,
        "keywords": [
            "genre plan",
            "genre planning",
            "plan schema",
            "planning schema",
            "buildable plan",
            "turn a genre preset into a buildable plan",
            "player outcome",
            "dominant tension",
            "loop ladder",
            "state owner",
            "accessibility envelope",
            "validation ladder",
            "genre gallery",
            "contrast set",
            "sandbox survival",
            "sandbox-survival",
            "tower defense",
            "tower-defense",
            "4X",
            "rhythm-action",
            "rhythm action",
            "management sim",
            "management-sim",
            "immersive sim",
            "immersive-sim",
        ],
        "discipline": "genre",
        "skills": ["feature-brief", "qa-matrix", "scope-rescue"],
        "agents": ["game_designer", "technical_director", "producer"],
        "docs": [
            "docs/reference/genre-plan.md",
            "docs/examples/genre-plan-example.md",
            "docs/examples/genre-gallery-example.md",
            "docs/research/game-development/genre/genre-plan.md",
            "docs/research/game-development/genre/genre-guide.md",
            "docs/research/game-development/genre/genre-patterns.md",
            "docs/research/game-development/genre/genre-examples.md",
            "docs/research/game-development/genre/genre-maturity.md",
            "docs/reference/genre-presets.md",
            "studio/docs/active/genre-starter.md",
        ],
        "validation_steps": [
            "Name the player outcome, dominant tension, contrast set, and loop ladder before implementation.",
            "Name the canonical owner, accessibility envelope, performance envelope, and first slice before implementation.",
            "Keep the plan schema, preset, playbook, and example matrix synchronized.",
        ],
    },
    {
        "name": "genre / software patterns",
        "priority": 2,
        "keywords": [
            "genre",
            "genre plan",
            "genre planning",
            "genre pattern",
            "pattern catalog",
            "contrast set",
            "genre family",
            "genre architecture",
            "genre support",
            "genre maturity",
            "software pattern",
            "example matrix",
            "preset",
            "playbook",
            "co-op survival",
            "co-op-survival",
            "cozy sim",
            "cozy-sim",
            "extraction-lite",
            "extraction lite",
            "narrative adventure",
            "platformer",
            "puzzle",
            "tactical rpg",
            "tactical-rpg",
            "genre gallery",
            "contrast set",
            "sandbox survival",
            "sandbox-survival",
            "tower defense",
            "tower-defense",
            "4X",
            "rhythm-action",
            "rhythm action",
            "management sim",
            "management-sim",
            "immersive sim",
            "immersive-sim",
        ],
        "discipline": "genre",
        "skills": ["feature-brief", "qa-matrix", "scope-rescue"],
        "agents": ["game_designer", "technical_director", "producer"],
        "docs": [
            "docs/reference/genre-plan.md",
            "docs/examples/genre-plan-example.md",
            "docs/examples/genre-gallery-example.md",
            "docs/research/game-development/genre/genre-plan.md",
            "docs/research/game-development/genre/genre-guide.md",
            "docs/research/game-development/genre/genre-patterns.md",
            "docs/research/game-development/genre/genre-examples.md",
            "docs/research/game-development/genre/genre-maturity.md",
            "docs/reference/genre-presets.md",
            "studio/docs/active/genre-starter.md",
        ],
        "validation_steps": [
            "If the task is planning-oriented, name the player outcome, dominant tension, contrast set, loop ladder, state owner, accessibility envelope, and validation ladder first.",
            "Name the dominant genre tension before choosing a pattern.",
            "Pick one software pattern family and one contrast set before implementation.",
            "State the first slice and the first system that will break if the genre is shallow.",
            "Keep the preset, playbook, pattern catalog, and example matrix synchronized.",
        ],
    },
    {
        "name": "gpu / rendering / communication",
        "priority": 3,
        "keywords": [
            "gpu",
            "cpu gpu",
            "cpu-gpu",
            "shader",
            "compute",
            "compute shader",
            "renderdoc",
            "graphicsbuffer",
            "graphics buffer",
            "rendering device",
            "renderingdevice",
            "rendering server",
            "renderingserver",
            "drawmeshinstancedindirect",
            "multimesh",
            "instancing",
            "instanced static mesh",
            "hierarchical instanced static mesh",
            "nanite",
            "hlod",
            "gpu culling",
            "readback",
            "upload",
            "vram",
            "overdraw",
        ],
        "discipline": "gpu",
        "skills": ["perf-pass", "qa-matrix", "feature-brief"],
        "agents": ["performance_analyst", "technical_director", "rendering_programmer"],
        "docs": [
            "docs/reference/gpu-guide.md",
            "docs/examples/gpu-example.md",
            "docs/reference/perf-guide.md",
            "docs/examples/perf-example.md",
            "docs/reference/advanced-perf-guide.md",
            "docs/examples/advanced-perf-example.md",
        ],
        "validation_steps": [
            "Name the CPU owner, the GPU owner, and the data contract before implementation.",
            "Capture one baseline measurement or capture before tuning.",
            "State the upload path, buffer shape, and readback policy before changing code.",
            "Keep the first lever and fallback lever explicit so the chosen representation can be defended.",
        ],
    },
    {
        "name": "audio / animation / presentation",
        "priority": 4,
        "keywords": [
            "audio",
            "sound",
            "music",
            "sfx",
            "voice",
            "ses",
            "müzik",
            "seslendirme",
            "animasyon",
            "animation playback",
            "animation timing",
            "animation event",
            "animation blueprint",
            "animation tree",
            "animation player",
            "animator",
            "sequencer",
            "timeline",
            "notify",
            "lip sync",
            "footstep",
            "telegraph",
            "cue",
            "presentation",
            "sync",
            "motion",
        ],
        "discipline": "presentation",
        "skills": ["audio-style-pack", "content-pipeline", "feature-brief"],
        "agents": ["audio_director", "technical_artist", "ui_programmer"],
        "docs": ["docs/reference/audio-animation-guide.md", "docs/examples/audio-animation-example.md"],
        "validation_steps": [
            "Name the playback owner, timing owner, and gameplay owner before implementation.",
            "Choose the simplest valid playback path before adding mix, graph, or sequencer complexity.",
            "Keep the gameplay truth separate from presentation callbacks and document the proof path.",
        ],
    },
    {
        "name": "engine bugs / troubleshooting / common errors",
        "priority": 2,
        "keywords": [
            "engine troubleshooting",
            "engine troubleshooting guide",
            "engine troubleshooting notes",
            "common engine bugs",
            "common engine errors",
            "common errors",
            "bugs",
            "bug families",
            "first check",
            "first checks",
            "debug surface",
            "debugger panel",
            "output log",
            "stack trace",
            "console stack trace",
            "null reference",
            "missing reference",
            "node path drift",
            "node path",
            "signal wiring",
            "signal",
            "warning system",
            "script execution order",
            "prefab override",
            "addressables",
            "uobject lifetime",
            "actor lifecycle",
            "live coding mismatch",
            "packaged build failure",
            "cook failure",
            "export failure",
            "editor only",
            "runtime only",
            "works in editor",
            "pie only",
            "serialization drift",
            "ownership boundary",
            "godot troubleshooting",
            "unity nullreferenceexception",
            "unreal output log",
        ],
        "discipline": "engine_bugs",
        "skills": ["bug-triage", "qa-matrix", "engine-setup"],
        "agents": ["qa_lead", "technical_director", "engine_programmer", "docs_researcher"],
        "docs": [
            "docs/reference/engine-bugs.md",
            "docs/examples/engine-bugs-example.md",
            "docs/research/game-development/foundations/engine-bugs.md",
            "docs/reference/engine-map.md",
            "docs/reference/engine-atlas.md",
            "docs/reference/system-atlas.md",
            "studio/docs/templates/bug-report.md",
            "studio/docs/templates/crash-triage.md",
        ],
        "validation_steps": [
            "Name the engine family, the likely bug family, and the first debug surface before patching.",
            "Separate editor-only, runtime-only, and packaged-build-only failures before deciding on a fix.",
            "If the task is a concrete repro, switch to the bugfix bundle after classification.",
        ],
    },
    {
        "name": "bug / crash / regression",
        "priority": 0,
        "keywords": ["bug", "crash", "soft lock", "regression", "issue", "broken", "freeze", "hotfix", "rollback", "incident", "live issue"],
        "discipline": "bugfix",
        "skills": ["bug-triage", "patch-hotfix", "qa-matrix"],
        "agents": ["qa_tester", "qa_lead", "lead_programmer"],
        "docs": ["studio/docs/templates/bug-report.md", "studio/docs/templates/crash-triage.md", "studio/docs/templates/release-checklist.md"],
        "validation_steps": [
            "Reproduce the bug first.",
            "Name the smallest safe rollback or hotfix path before broad implementation.",
            "Document the smallest validation loop after the fix lands.",
        ],
    },
    {
        "name": "advanced performance / algorithms",
        "priority": 2,
        "keywords": [
            "advanced optimization",
            "optimization algorithm",
            "optimization algorithms",
            "algorithmic optimization",
            "occlusion",
            "culling",
            "lod",
            "hlod",
            "nanite",
            "instancing",
            "batching",
            "spatial partitioning",
            "spatial hash",
            "quadtree",
            "octree",
            "bvh",
            "sweep and prune",
            "dirty region",
            "delta compression",
            "interest management",
            "job system",
            "jobs",
            "burst",
            "ecs",
            "mass",
            "simd",
            "vectorization",
            "multithread",
            "worker",
            "streaming",
            "visibility cache",
            "broadphase",
            "data-oriented",
            "data oriented",
        ],
        "discipline": "performance",
        "skills": ["perf-pass", "qa-matrix", "feature-brief"],
        "agents": ["performance_analyst", "technical_director", "rendering_programmer"],
        "docs": [
            "docs/reference/advanced-perf-guide.md",
            "docs/examples/advanced-perf-example.md",
            "docs/reference/perf-guide.md",
            "docs/reference/genre-perf-guide.md",
        ],
        "validation_steps": [
            "Name the algorithm family before changing code.",
            "Capture one baseline measurement before tuning.",
            "Keep the first algorithmic lever and the fallback lever explicit.",
            "Check whether the problem is really spatial partitioning, culling, batching, or data-oriented execution before escalating.",
        ],
    },
    {
        "name": "benchmark / measurement",
        "priority": 5,
        "keywords": [
            "benchmark",
            "benchmarking",
            "bench",
            "measurement",
            "measure",
            "metric",
            "metrics",
            "baseline",
            "threshold",
            "scorecard",
            "leaderboard",
            "harness",
            "evaluation harness",
            "regression suite",
            "swe-bench",
            "agentbench",
            "gaia",
            "osworld",
            "webarena",
            "openai evals",
        ],
        "discipline": "benchmark",
        "skills": ["qa-matrix", "perf-pass", "feature-brief"],
        "agents": ["qa_lead", "technical_director", "performance_analyst"],
        "docs": [
            "docs/reference/benchmark-guide.md",
            "docs/examples/benchmark-example.md",
            "docs/reference/perf-guide.md",
            "docs/reference/eval-strategy.md",
        ],
        "validation_steps": [
            "Name the benchmark family before comparing results.",
            "Name the baseline, metric, threshold, and artifact before measuring.",
            "Keep the benchmark guide, example, runner, and eval plan synchronized.",
        ],
    },
    {
        "name": "quality / optimization",
        "priority": 0,
        "keywords": [
            "quality",
            "code quality",
            "quality control",
            "quality process",
            "maintainability",
            "readability",
            "refactor",
            "refactoring",
            "cleanup",
            "clean up",
            "simplify",
            "technical debt",
            "design debt",
            "review",
            "code review",
            "quality bar",
            "quality criteria",
            "quality gate",
            "go/no-go",
            "review process",
            "evidence",
            "optimization criteria",
            "optimize",
            "optimization",
            "maintainable",
            "self-documenting",
            "kalite",
            "kod kalitesi",
            "okunabilirlik",
            "bakım",
            "bakim",
            "iyileştirme",
            "iyilestirme",
            "temizlik",
            "refaktör",
            "refaktor",
            "optimizasyon",
            "performans",
        ],
        "discipline": "quality",
        "skills": ["feature-brief", "qa-matrix", "perf-pass"],
        "agents": ["technical_director", "qa_lead", "performance_analyst"],
        "docs": [
            "docs/reference/quality-guide.md",
            "docs/reference/quality-process.md",
            "docs/examples/quality-example.md",
            "docs/examples/quality-process-example.md",
            "docs/reference/code-review.md",
            "docs/reference/perf-guide.md",
            "docs/examples/perf-example.md",
            "docs/reference/advanced-perf-guide.md",
            "docs/examples/advanced-perf-example.md",
        ],
        "validation_steps": [
            "Name the runtime owner, data owner, and editor owner before refactoring.",
            "Name the quality-control process step, the evidence artifact, and the go/no-go gate.",
            "State the validation path before changing implementation details.",
            "If optimization is in scope, capture the baseline, the first lever, and the fallback lever before tuning.",
        ],
    },
    {
        "name": "performance",
        "keywords": [
            "fps",
            "frame",
            "perf",
            "performance",
            "memory",
            "hitch",
            "stutter",
            "battery",
            "thermal",
            "alloc",
            "allocation",
            "pool",
            "pooling",
            "instancing",
            "multimesh",
            "ecs",
            "dots",
            "burst",
            "mass",
        ],
        "discipline": "performance",
        "skills": ["perf-pass", "mobile-optimization", "web-build-readiness"],
        "agents": ["performance_analyst", "technical_director", "rendering_programmer"],
        "docs": [
            "docs/reference/perf-guide.md",
            "docs/reference/genre-perf-guide.md",
            "docs/examples/perf-example.md",
            "docs/examples/genre-perf-example.md",
            "studio/docs/templates/perf-pass.md",
        ],
        "validation_steps": [
            "Name the genre family and the dominant pressure before changing code.",
            "Capture one baseline measurement before tuning.",
            "Name the first genre lever and the fallback lever before changing code.",
            "Check whether representation choice is the real bottleneck before micro-optimizing.",
            "Record the expected perf target in the active docs.",
        ],
    },
    {
        "name": "multiplayer / backend",
        "keywords": ["multiplayer", "coop", "co-op", "netcode", "backend", "lobby", "server", "matchmaking", "sync"],
        "discipline": "backend",
        "skills": ["multiplayer-slice", "backend-foundation", "security-threat-model"],
        "agents": ["network_programmer", "backend_engineer", "security_engineer"],
        "docs": ["studio/docs/templates/feature-brief.md", "studio/docs/templates/telemetry-schema.md"],
        "validation_steps": ["State the authority model.", "Define the narrowest sync test before broad implementation."],
    },
    {
        "name": "save / persistence",
        "keywords": ["save", "checkpoint", "load", "profile", "migration", "cloud save"],
        "discipline": "save",
        "skills": ["save-system", "qa-matrix", "security-threat-model"],
        "agents": ["save_system_engineer", "qa_lead", "security_engineer"],
        "docs": ["studio/docs/templates/save-migration-plan.md", "studio/docs/templates/test-plan.md"],
        "validation_steps": ["Define the save/load happy path.", "Cover one corruption or migration failure mode."],
    },
    {
        "name": "combat / gameplay",
        "keywords": [
            "combat",
            "enemy",
            "boss",
            "character",
            "player",
            "avatar",
            "ability",
            "skill",
            "skills",
            "skill tree",
            "skill trees",
            "upgrade",
            "upgrades",
            "perk",
            "perks",
            "passive",
            "passives",
            "cooldown",
            "cooldowns",
            "boon",
            "boons",
            "unlock",
            "unlocks",
            "meta unlock",
            "meta unlocks",
            "weapon",
            "movement",
            "mechanic",
            "damage",
            "health",
            "hitbox",
            "hurtbox",
            "projectile",
            "pathfinding",
            "navigation",
            "navmesh",
            "astar",
            "raycast",
            "eqs",
            "state tree",
            "state-tree",
            "gameplay ability system",
            "gas",
            "take damage",
            "interact",
            "interaction",
            "pickup",
            "pickups",
            "loot",
            "craft",
            "crafting",
            "recipe",
            "recipes",
            "gathering",
            "workbench",
            "forge",
            "chest",
            "lever",
            "prompt",
            "world object",
            "companion",
            "companions",
            "follower",
            "followers",
            "squad",
            "formation",
        ],
        "discipline": "gameplay",
        "skills": ["combat-loop", "mechanic-design", "gameplay-slice"],
        "agents": ["combat_designer", "gameplay_programmer", "qa_tester"],
        "docs": ["studio/docs/templates/feature-brief.md", "studio/docs/templates/enemy-archetype.md"],
        "validation_steps": [
            "Write down the readable input-to-feedback loop.",
            "State the world stack, navigation model, and damage/contact model before scaling the slice.",
            "Keep one manual or automated proof path for the slice.",
        ],
    },
    {
        "name": "narrative / lorebook",
        "keywords": ["lorebook", "lore book", "world bible", "story bible", "canon", "codex", "archive", "bestiary", "world knowledge"],
        "discipline": "narrative",
        "skills": ["narrative-pipeline", "quest-flow", "content-pipeline"],
        "agents": ["narrative_director", "quest_designer", "localization_lead"],
        "docs": [
            "docs/reference/lorebook-methodology.md",
            "studio/docs/templates/lorebook-brief.md",
            "docs/examples/lorebook-example.md",
            "studio/docs/templates/quest-brief.md",
        ],
        "validation_steps": [
            "Define the canon scope and the systems that own it.",
            "Separate unlock rules from the text entries themselves.",
            "Verify one lookup path, one unlock path, and one save/load resume path.",
        ],
    },
    {
        "name": "narrative / world graph",
        "priority": 2,
        "keywords": [
            "world graph",
            "relationship graph",
            "faction network",
            "history network",
            "timeline",
            "chronology",
            "lineage",
            "biography",
            "organization",
            "org chart",
            "social graph",
            "history",
            "histories",
            "event chain",
            "canon map",
            "map state",
        ],
        "discipline": "narrative",
        "skills": ["narrative-pipeline", "content-pipeline", "quest-flow"],
        "agents": ["narrative_director", "quest_designer", "technical_director"],
        "docs": [
            "docs/reference/world-graph-methodology.md",
            "studio/docs/templates/world-graph-brief.md",
            "docs/examples/world-graph-example.md",
            "studio/docs/templates/lorebook-brief.md",
            "studio/docs/templates/quest-brief.md",
        ],
        "validation_steps": [
            "Define the canonical node and edge types before adding content.",
            "Specify which history beats are append-only and which are snapshot-backed.",
            "Name the cached or indexed read path for the common graph query.",
        ],
    },
    {
        "name": "narrative / quest",
        "keywords": ["narrative", "story", "dialogue", "quest", "mission", "cutscene", "branching conversation"],
        "discipline": "narrative",
        "skills": ["narrative-pipeline", "quest-flow", "localization-pass"],
        "agents": ["narrative_director", "quest_designer", "localization_lead"],
        "docs": ["studio/docs/templates/quest-brief.md", "studio/docs/templates/localization-glossary.md"],
        "validation_steps": ["Define branching or state rules up front.", "Verify one happy path and one recovery path."],
    },
    {
        "name": "ui / ux / accessibility",
        "keywords": [
            "ui",
            "hud",
            "menu",
            "template",
            "templates",
            "theme",
            "widget",
            "widgets",
            "ux",
            "settings",
            "tutorial",
            "accessibility",
            "subtitle",
            "input",
            "controls",
            "controller",
            "gamepad",
            "keyboard",
            "mouse",
            "remap",
            "rebind",
            "pause",
            "camera",
            "focus",
            "navigation",
            "screen",
            "onboarding",
            "layout",
            "uxml",
            "uss",
            "ui builder",
            "ui toolkit",
            "commonui",
            "umg",
            "viewmodel",
        ],
        "discipline": "ui-ux",
        "skills": ["ui-flow", "tutorial-onboarding", "accessibility-audit"],
        "agents": ["ux_designer", "ui_programmer", "accessibility_specialist"],
        "docs": [
            "docs/reference/ui-guide.md",
            "docs/examples/ui-example.md",
            "studio/docs/templates/accessibility-pass.md",
            "studio/docs/templates/feature-brief.md",
        ],
        "validation_steps": [
            "List all intended states.",
            "Name the screen owner, the projection boundary, and the template source.",
            "Confirm the critical player prompt remains readable.",
        ],
    },
    {
        "name": "assets / content pipeline",
        "keywords": [
            "asset",
            "assets",
            "asset management",
            "asset bundle",
            "asset bundles",
            "addressables",
            "asset database",
        "asset manager",
        "asset registry",
        "import",
        "import boundary",
        "import boundaries",
        "ownership",
        "data asset",
        "primary data asset",
        "scriptableobject",
        "resource loader",
        "packedscene",
        "prefab",
        "reimport",
        "compression",
        "soft reference",
        "hard reference",
        "runtime owner",
        "shared data",
        "source asset",
        "runtime asset",
        "source art",
        "import root",
        "load path",
        "load boundary",
        "load boundaries",
        "streamable",
        "package",
    ],
        "discipline": "assets",
        "skills": ["content-pipeline", "tools-pipeline", "feature-brief"],
        "agents": ["technical_artist", "tools_programmer", "producer"],
        "docs": ["docs/reference/asset-guide.md", "docs/examples/asset-example.md", "docs/research/game-development/assets/README.md"],
        "validation_steps": [
            "Name the source asset, runtime owner, and import/load boundary.",
            "State whether the asset should stay local, be shared, or be streamable.",
        ],
    },
    {
        "name": "visuals / animation / presentation",
        "keywords": [
            "sprite",
            "sprites",
            "sprite sheet",
            "spritesheet",
            "texture",
            "textures",
            "image",
            "images",
            "icon",
            "icons",
            "animation",
            "animated",
            "flipbook",
            "particle",
            "particles",
            "vfx",
            "visual effect",
            "visual effects",
        ],
        "discipline": "content-pipeline",
        "skills": ["art-style-pack", "content-pipeline", "ui-flow"],
        "agents": ["art_director", "technical_artist", "ui_programmer"],
        "docs": ["studio/docs/templates/art-direction-lite.md", "studio/docs/templates/content-pipeline.md"],
        "validation_steps": [
            "State the source art, the playback owner, and whether the presentation is world-facing or UI-facing.",
            "Document the import, atlas, or animation ownership before implementation.",
        ],
    },
    {
        "name": "art / audio / content pipeline",
        "keywords": ["art", "style", "vfx", "audio", "sound", "pipeline", "import", "content"],
        "discipline": "content-pipeline",
        "skills": ["art-style-pack", "audio-style-pack", "content-pipeline"],
        "agents": ["art_director", "audio_director", "technical_artist"],
        "docs": ["studio/docs/templates/art-direction-lite.md", "studio/docs/templates/content-pipeline.md"],
        "validation_steps": ["Define the content handoff path.", "Validate naming or import assumptions before scale grows."],
    },
    {
        "name": "handoff / traceability / doc sync",
        "keywords": [
            "handoff",
            "handover",
            "traceability",
            "doc sync",
            "docs sync",
            "sync docs",
            "refresh docs",
            "release note",
            "release notes",
        ],
        "discipline": "research",
        "skills": ["feature-brief", "qa-matrix", "project-radar"],
        "agents": ["producer", "technical_director", "qa_lead"],
        "docs": ["studio/docs/templates/handoff-contract.md", "studio/docs/templates/feature-traceability.md"],
        "validation_steps": [
            "Link scope, evidence, risk, validation, owner, blockers, and next step.",
            "Verify the feature maps to decision, implementation, tests, and release impact.",
        ],
    },
    {
        "name": "agent transcript / conversation history",
        "priority": 2,
        "keywords": [
            "agent transcript",
            "conversation transcript",
            "task assignment history",
            "assignment history",
            "agent-to-agent",
            "agent to agent",
            "inter-agent",
            "handoff history",
            "message history",
            "conversation log",
            "worker transcript",
            "transcript entry",
        ],
        "discipline": "transcript",
        "skills": ["feature-brief", "qa-matrix", "project-radar"],
        "agents": ["producer", "technical_director", "qa_lead"],
        "docs": [
            "docs/reference/agent-transcript.md",
            "docs/examples/agent-transcript-example.md",
            "docs/research/game-development/foundations/agent-transcript.md",
            "docs/reference/prompt-journal.md",
            "docs/examples/prompt-journal-example.md",
            "studio/docs/active/agent-transcript.md",
            "studio/docs/active/eval-agent-transcript.md",
        ],
        "validation_steps": [
            "Keep the task assignment history and conversation turns in the transcript, not in the prompt journal.",
            "Keep prompt history, transcript, and handoff docs linked when the work should be reopened later.",
            "Keep single-specialist mode visible if the transcript work is actually narrow.",
        ],
    },
    {
        "name": "prompt history / agent journal",
        "priority": 2,
        "keywords": [
            "prompt history",
            "agent journal",
            "step journal",
            "prompt log",
            "step log",
            "history trail",
            "audit trail",
            "review later",
            "journal entry",
            "entry log",
            "expected found improved",
        ],
        "discipline": "journal",
        "skills": ["feature-brief", "qa-matrix", "project-radar"],
        "agents": ["producer", "technical_director", "qa_lead"],
        "docs": [
            "docs/reference/prompt-journal.md",
            "docs/examples/prompt-journal-example.md",
            "studio/docs/active/prompt-journal.md",
            "studio/docs/active/eval-prompt-journal.md",
        ],
        "validation_steps": [
            "Capture the user prompt once and keep the record append-only.",
            "Write one agent journal entry with expectation, found, improvement, and evaluation.",
            "Keep the guide, example, active journal, and eval plan in sync.",
        ],
    },
    {
        "name": "versioning / release metadata",
        "priority": 1,
        "keywords": [
            "versioning",
            "version",
            "VERSION",
            "semver",
            "semantic version",
            "changelog",
            "release tag",
            "tag policy",
            "tag",
            "bump version",
            "prerelease",
            "pre-release",
            "release metadata",
        ],
        "discipline": "versioning",
        "skills": ["release-gate", "feature-brief", "qa-matrix"],
        "agents": ["release_manager", "build_release_engineer", "technical_director"],
        "docs": [
            "docs/reference/version-guide.md",
            "docs/examples/version-example.md",
            "docs/research/game-development/production/versioning.md",
            "studio/docs/templates/release-checklist.md",
            "CHANGELOG.md",
            "VERSION",
        ],
        "validation_steps": [
            "Identify the canonical version file and tag family before editing release metadata.",
            "Keep VERSION, CHANGELOG.md, and artifact labels aligned with the release checklist.",
        ],
    },
    {
        "name": "release hardening / code protection",
        "priority": 5,
        "keywords": [
            "release hardening",
            "hardening",
            "code protection",
            "protected build",
            "protected release",
            "protected shipping",
            "build protection",
            "build integrity",
            "symbol policy",
            "symbol archive",
            "crash symbols",
            "debug symbols",
            "dedicated server",
            "server authoritative",
            "server-authoritative",
            "authority boundary",
            "trust boundary",
            "stripping",
            "obfuscation",
            "encryption",
            "pck encryption",
            "script encryption",
            "multiplayer trust",
            "shipping build",
            "release protection",
        ],
        "discipline": "release_hardening",
        "skills": ["build-pipeline", "multiplayer-slice", "security-threat-model", "qa-matrix"],
        "agents": ["release_manager", "build_release_engineer", "security_engineer", "network_programmer", "qa_lead"],
        "docs": [
            "docs/reference/release-hardening-guide.md",
            "docs/examples/release-hardening-example.md",
            "docs/research/game-development/production/release-hardening.md",
            "docs/reference/ci-cd.md",
            "docs/reference/platform-guide.md",
            "docs/research/game-development/production/platform.md",
            "docs/research/game-development/production/incident.md",
            "docs/research/game-development/production/release-validation.md",
            "studio/docs/templates/release-checklist.md",
            "studio/docs/templates/release-hardening.md",
            "studio/docs/active/eval-release-hardening.md",
        ],
        "validation_steps": [
            "Name the build command, code-protection layer, trust boundary, symbol policy, and rollback owner before implementation.",
            "Separate multiplayer authority from client-side protection and keep the dedicated-server or fallback split explicit.",
            "Keep the guide, example, research note, checklist, and eval plan synchronized.",
        ],
    },
    {
        "name": "sector / current signals",
        "priority": 4,
        "keywords": [
            "sector",
            "sector intel",
            "sector intelligence",
            "industry intelligence",
            "market intelligence",
            "current signals",
            "trend watch",
            "game industry",
            "games industry",
            "state of the game industry",
            "developer satisfaction survey",
            "essential facts",
            "steam hardware survey",
            "platform policy",
            "policy update",
            "current reports",
        ],
        "discipline": "sector",
        "skills": ["project-radar", "qa-matrix"],
        "agents": ["producer", "technical_director", "community_manager"],
        "docs": [
            "docs/reference/sector-intel.md",
            "docs/examples/sector-intel-example.md",
            "docs/research/game-development/production/sector-intel.md",
            "docs/research/game-development/production/README.md",
        ],
        "validation_steps": [
            "Name the source family and current date window before summarizing.",
            "Separate facts from inference and state one repo implication.",
            "Keep the guide, example, research note, checklist, and eval plan synchronized.",
        ],
    },
    {
        "name": "marketing / intel / chart pack",
        "priority": 5,
        "keywords": [
            "marketing intel",
            "marketing intelligence",
            "marketing status",
            "current marketing",
            "current status",
            "campaign status",
            "campaign health",
            "marketing dashboard",
            "dashboard",
            "chart pack",
            "chart",
            "charts",
            "graph",
            "graphs",
            "trend",
            "trends",
            "snapshot",
            "report",
            "reports",
            "statistics",
            "statistic",
            "stats",
            "kpi",
            "metric movement",
            "metrics",
            "son durum",
            "güncel durum",
            "guncel durum",
            "istatistik",
            "grafik",
            "grafikler",
            "rapor",
        ],
        "discipline": "marketing_intel",
        "skills": ["data-telemetry", "community-ops", "project-radar"],
        "agents": ["analytics_engineer", "producer", "community_manager", "release_manager"],
        "docs": [
            "docs/reference/marketing-intel.md",
            "docs/examples/marketing-intel-example.md",
            "docs/research/game-development/production/marketing-intel.md",
            "docs/reference/marketing-guide.md",
            "docs/reference/sector-intel.md",
            "docs/reference/steam-intel.md",
            "docs/research/game-development/production/marketing.md",
            "docs/research/game-development/production/README.md",
            "studio/docs/templates/marketing-intel.md",
            "studio/docs/templates/telemetry-schema.md",
        ],
        "validation_steps": [
            "Name the source family and current window before charting.",
            "Separate facts, charted metrics, and repo implications.",
            "Keep the guide, example, research note, checklist, and eval plan synchronized.",
        ],
    },
    {
        "name": "marketing / strategy / measurement",
        "priority": 5,
        "keywords": [
            "marketing",
            "marketing strategy",
            "marketing plan",
            "campaign",
            "campaign strategy",
            "go to market",
            "go-to-market",
            "funnel",
            "wishlist",
            "wishlist conversion",
            "store page strategy",
            "product page",
            "message house",
            "channel mix",
            "creator outreach",
            "influencer outreach",
            "press kit",
            "launch messaging",
            "demo strategy",
            "promotion strategy",
            "paid acquisition",
            "organic growth",
            "analytics",
            "measurement",
            "conversion",
            "ctr",
            "audience",
            "positioning",
        ],
        "discipline": "marketing",
        "skills": ["storefront-launch", "marketing-beat-brief", "community-ops", "release-gate", "data-telemetry"],
        "agents": ["producer", "community_manager", "release_manager", "analytics_engineer", "art_director"],
        "docs": [
            "docs/reference/marketing-guide.md",
            "docs/examples/marketing-example.md",
            "docs/research/game-development/production/marketing.md",
            "docs/reference/sector-intel.md",
            "docs/examples/sector-intel-example.md",
            "docs/research/game-development/production/sector-intel.md",
            "docs/research/game-development/production/README.md",
            "studio/docs/templates/marketing-plan.md",
            "studio/docs/templates/marketing-brief.md",
            "studio/docs/templates/storefront-checklist.md",
            "studio/docs/templates/community-ops.md",
        ],
        "validation_steps": [
            "Name the objective, audience, channel family, and baseline before recommending a strategy.",
            "Separate facts from inference and say which asset or metric will prove the plan.",
            "Keep the guide, example, research note, checklist, and eval plan synchronized.",
        ],
    },
    {
        "name": "release / storefront / marketing",
        "keywords": ["release", "launch", "store", "steam", "festival", "marketing", "announcement", "wishlist"],
        "discipline": "release",
        "skills": ["storefront-launch", "marketing-beat-brief", "release-gate"],
        "agents": ["release_manager", "community_manager", "art_director"],
        "docs": ["studio/docs/templates/storefront-checklist.md", "studio/docs/templates/marketing-brief.md", "studio/docs/templates/release-checklist.md"],
        "validation_steps": ["Confirm the artifact path.", "Write down known issues and the go/no-go gate."],
    },
    {
        "name": "console / compliance / porting",
        "keywords": ["console", "ps5", "ps5-like", "cert", "submission", "port", "switch", "playstation", "xbox", "compliance", "rating"],
        "discipline": "console",
        "skills": ["porting-plan", "console-cert-readiness", "compliance-age-rating"],
        "agents": ["porting_engineer", "certification_manager", "release_manager"],
        "docs": [
            "docs/reference/console-guide.md",
            "docs/examples/console-example.md",
            "docs/research/game-development/production/console.md",
            "studio/checklists/discipline/console.toml",
            "studio/docs/active/eval-console.md",
            "studio/docs/templates/cert-checklist.md",
            "studio/docs/templates/platform-targets.md",
        ],
        "validation_steps": [
            "Document the target platform holder, family split, and submission gate.",
            "Capture one cert-risk or compliance assumption.",
        ],
    },
    {
        "name": "mobile",
        "keywords": ["mobile", "ios", "android", "touch", "battery", "thermal", "free to play", "f2p"],
        "discipline": "mobile",
        "skills": ["mobile-optimization", "monetization-guardrails", "data-telemetry"],
        "agents": ["porting_engineer", "monetization_guardian", "analytics_engineer"],
        "docs": ["studio/docs/templates/monetization-guardrails.md", "studio/docs/templates/telemetry-schema.md"],
        "validation_steps": ["Define the session and input assumptions.", "Confirm battery or monetization risks are documented."],
    },
]


def build_result(
    route: dict[str, object],
    include_genre: bool,
    engine_slug: str,
    agent_model_overrides: list[str] | None = None,
) -> dict[str, object]:
    discipline = str(route.get("discipline", "research"))
    discipline_stack = [discipline]
    if str(route.get("name", "")) == "advanced performance / algorithms":
        discipline_stack.append("advanced_performance")
    for extra_discipline in route.get("extra_disciplines", []) or []:
        discipline_stack.append(str(extra_discipline))
    checklist_disciplines = expand_disciplines_for_checklists(discipline_stack)
    engine_summary = starter_kit_summary(engine_slug)
    task_text = str(route.get("task_text", ""))
    agent_titles = [agent_public_title(agent) for agent in route["agents"]]
    if discipline == "mastermind":
        agent_titles = [agent_public_title("mastermind"), *agent_titles]
    agent_models, unused_overrides = resolve_agent_model_profiles(list(route["agents"]), agent_model_overrides)
    result = {
        "route": route["name"],
        "skills": route["skills"],
        "agents": route["agents"],
        "agent_titles": agent_titles,
        "agent_models": agent_models,
        "docs": route["docs"],
        "checklists": resolve_checklists(engine_slug=engine_slug, disciplines=checklist_disciplines),
        "engine_kit": engine_summary,
        "engine_actions": engine_summary["smoke_commands"] + engine_summary["export_commands"],
        "research_refs": related_research_refs(checklist_disciplines, engine_slug=engine_slug, task_text=task_text),
        "validation_steps": route.get("validation_steps", []),
    }
    if agent_model_overrides:
        result["agent_model_overrides"] = parse_agent_model_overrides(agent_model_overrides)
    if unused_overrides:
        result["agent_model_warnings"] = [f"Override '{item}' did not match any selected agent." for item in unused_overrides]
    if include_genre:
        active_genre = detect_active_genre()
        if active_genre:
            metadata = parse_preset_metadata(preset_path("genre", active_genre))
            sections = metadata.get("sections", {})
            result["genre"] = {
                "slug": active_genre,
                "name": metadata.get("display_name", active_genre),
                "summary": metadata.get("summary", ""),
                "skills": sections.get("Recommended first skills", []),
                "docs": ["studio/docs/active/genre-starter.md"],
            }
    return result


def main() -> int:
    parser = argparse.ArgumentParser(description="Recommend likely skills, agents, and docs for a given task description.")
    parser.add_argument("task", help="Natural language task description.")
    parser.add_argument("--engine", help="Optional engine slug override.")
    parser.add_argument(
        "--agent-model",
        dest="agent_models",
        action="append",
        help="Override a selected agent model with agent=model (repeatable; comma-separated pairs allowed).",
    )
    parser.add_argument("--json", action="store_true", help="Emit machine-readable JSON.")
    args = parser.parse_args()

    try:
        match_context = build_match_context(args.task)
        scores = []
        for route in ROUTES:
            score = sum(1 for kw in route["keywords"] if keyword_matches_context(match_context, kw))
            if score:
                scores.append((score, route.get("priority", 1), route))
        scores.sort(key=lambda item: (item[0], item[1]), reverse=True)

        resolved_engine = args.engine or infer_engine_from_text(args.task) or primary_engine_slug()
        if not scores:
            engine_summary = starter_kit_summary(resolved_engine)
            result = {
                "route": "fallback",
                "skills": ["intake-router", "project-radar", "feature-brief"],
                "agents": ["producer", "technical_director", "game_designer"],
                "docs": ["studio/docs/active/current-sprint.md", "studio/docs/active/risk-register.md"],
                "checklists": resolve_checklists(engine_slug=resolved_engine, disciplines=["research"]),
                "engine_kit": engine_summary,
                "engine_actions": engine_summary["smoke_commands"] + engine_summary["export_commands"],
                "research_refs": related_research_refs(["research"], engine_slug=resolved_engine, task_text=args.task),
                "validation_steps": ["Clarify the task into one buildable slice.", "Link the task to a feature brief or active doc before implementation."],
            }
            agent_models, unused_overrides = resolve_agent_model_profiles(result["agents"], args.agent_models)
            result["agent_models"] = agent_models
            if args.agent_models:
                result["agent_model_overrides"] = parse_agent_model_overrides(args.agent_models)
            if unused_overrides:
                result["agent_model_warnings"] = [f"Override '{item}' did not match any selected agent." for item in unused_overrides]
        else:
            selected = dict(scores[0][2])
            selected["task_text"] = args.task
            result = build_result(selected, include_genre=True, engine_slug=resolved_engine, agent_model_overrides=args.agent_models)
    except ValueError as exc:
        raise SystemExit(str(exc))

    if args.json:
        print(json.dumps(result, indent=2))
    else:
        print(f"Route: {result['route']}")
        if "genre" in result:
            print(f"Genre lens: {result['genre']['name']}")
            if result["genre"]["summary"]:
                print(f"- {result['genre']['summary']}")
            if result["genre"]["skills"]:
                print("Genre skills:")
                for item in result["genre"]["skills"]:
                    print(f"- {item}")
        print("Skills:")
        for item in result["skills"]:
            print(f"- ${item}")
        print("Agents:")
        for item in result["agents"]:
            print(f"- {item}")
        print("Agent models:")
        for item in result.get("agent_models", []):
            suffix = f" ({item['model_reasoning_effort']})" if item.get("model_reasoning_effort") else ""
            print(f"- {item['public_title']} [{item['agent']}] -> {item['model']}{suffix}")
        if result.get("agent_model_overrides"):
            print("Agent model overrides:")
            for agent, model in result["agent_model_overrides"].items():
                print(f"- {agent} = {model}")
        for warning in result.get("agent_model_warnings", []):
            print(f"Model warning: {warning}")
        print("Docs:")
        for item in result["docs"]:
            print(f"- {item}")
        print("Checklists:")
        for item in result["checklists"]:
            print(f"- [{item['severity']}] {item['title']} ({item['source']})")
        print("Engine actions:")
        for item in result["engine_actions"]:
            print(f"- {item}")
        print("Research refs:")
        for item in result["research_refs"]:
            print(f"- {item}")
        print("Validation steps:")
        for item in result["validation_steps"]:
            print(f"- {item}")
        if "genre" in result:
            print("Genre docs:")
            for item in result["genre"]["docs"]:
                print(f"- {item}")
    return 0

if __name__ == "__main__":
    raise SystemExit(main())
