#!/usr/bin/env python3
from __future__ import annotations

from pathlib import Path

from _studio_common import REPO_ROOT

REQUIRED_PATHS = [
    "AGENTS.md",
    "README.md",
    "studio.toml",
    "CONTRIBUTING.md",
    "SECURITY.md",
    "SUPPORT.md",
    "CODE_OF_CONDUCT.md",
    ".env.example",
    "Makefile",
    ".github",
    ".github/CODEOWNERS",
    ".github/ISSUE_TEMPLATE",
    ".github/ISSUE_TEMPLATE/config.yml",
    ".github/ISSUE_TEMPLATE/bug-report.yml",
    ".github/ISSUE_TEMPLATE/feature-request.yml",
    ".github/ISSUE_TEMPLATE/infra-routing-change.yml",
    ".github/ISSUE_TEMPLATE/genre-preset-update.yml",
    ".github/pull_request_template.md",
    ".github/workflows",
    ".github/workflows/repo-validate.yml",
    ".github/workflows/docker-smoke.yml",
    ".github/workflows/starter-kit-contracts.yml",
    ".github/workflows/release-readiness.yml",
    ".github/workflows/nightly-audit.yml",
    ".github/dependabot.yml",
    "export_presets.cfg",
    ".codex/config.toml",
    ".codex/hooks.json",
    ".codex/agents",
    ".codex/agents/reviewer.toml",
    ".agents/skills",
    "docs/README.md",
    "docs/setup",
    "docs/setup/first-hour-walkthrough.md",
    "docs/setup/github-maintainer-setup.md",
    "docs/setup/optional-codex-hooks.md",
    "docs/setup/secrets-and-env.md",
    "docs/reference",
    "docs/reference/code-review.md",
    "docs/reference/ci-cd-architecture.md",
    "docs/reference/codex-compatibility.md",
    "docs/reference/engine-agent-guidelines.md",
    "docs/reference/engine-selection-guide.md",
    "docs/reference/eval-strategy.md",
    "docs/reference/genre-presets.md",
    "docs/reference/task-prompt-examples.md",
    "docs/reference/workflow-recipes.md",
    "docs/reference/handoff-contracts.md",
    "docs/reference/feature-traceability.md",
    "docs/reference/doc-sync-audit.md",
    "docs/reference/balance-simulator.md",
    "docs/examples",
    "docs/examples/README.md",
    "docs/examples/feature-brief-golden-example.md",
    "docs/examples/adr-golden-example.md",
    "docs/examples/qa-matrix-golden-example.md",
    "docs/examples/bug-report-golden-example.md",
    "docs/examples/perf-pass-golden-example.md",
    "docs/examples/postmortem-golden-example.md",
    "docs/examples/handoff-contract-golden-example.md",
    "docs/research",
    "docs/research/openai-codex-infra-findings.md",
    "docs/research/game-development/policy.md",
    "docs/research/game-development/templates/research-note.md",
    "docs/research/game-development/foundations/README.md",
    "docs/research/game-development/foundations/design-frameworks-mda-gameflow-and-sdt.md",
    "docs/research/game-development/foundations/game-feel-usability-and-accessibility-foundations.md",
    "docs/research/game-development/foundations/ai-pathfinding-and-decision-foundations.md",
    "docs/research/game-development/foundations/difficulty-balance-and-adaptation-foundations.md",
    "docs/research/game-development/engines/README.md",
    "docs/research/game-development/engines/godot-4-2d-3d-class-and-mechanic-guide.md",
    "docs/research/game-development/systems/gameplay-loop-state-and-update-architecture.md",
    "docs/research/game-development/systems/combat-damage-and-effects-architecture.md",
    "docs/research/game-development/systems/ai-navigation-and-entity-scale-architecture.md",
    "docs/research/game-development/systems/save-progression-and-runtime-data-architecture.md",
    "docs/research/game-development/systems/crafting-recipes-and-resource-flow-architecture.md",
    "docs/research/game-development/systems/dialogue-conversation-and-quest-state-architecture.md",
    "docs/research/game-development/systems/party-companion-and-squad-architecture.md",
    "docs/research/game-development/genre/genre-design-pattern-catalog.md",
    "docs/research/game-development/genre/genre-example-matrix.md",
    "docs/research/game-development/genre/deckbuilder-roguelike-architecture.md",
    "docs/research/game-development/genre/survivorlike-architecture.md",
    "docs/research/game-development/genre/colony-sim-architecture.md",
    "docs/research/game-development/genre/factory-automation-architecture.md",
    "docs/research/game-development/genre/metroidvania-architecture.md",
    "docs/research/game-development/engines/godot-4-2d-3d-navigation-damage-performance.md",
    "docs/research/game-development/engines/godot-4-class-editor-object-map.md",
    "docs/research/game-development/engines/unity-6-2d-3d-class-and-mechanic-guide.md",
    "docs/research/game-development/engines/unity-6-2d-3d-navigation-damage-performance.md",
    "docs/research/game-development/engines/unity-6-class-editor-object-map.md",
    "docs/research/game-development/engines/unreal-5-2d-3d-class-and-mechanic-guide.md",
    "docs/research/game-development/engines/unreal-5-2d-3d-navigation-damage-performance.md",
    "docs/research/game-development/engines/unreal-5-class-editor-object-map.md",
    "docs/research/game-development/production/platform-readiness-pc-web-mobile-console.md",
    "docs/research/game-development/production/incident-hotfix-and-rollback.md",
    "evals",
    "evals/doctor_surface/required_checks.json",
    "evals/godot_surface/expectations.json",
    "evals/route_task/cases.json",
    "evals/genre_guidance/cases.json",
    "evals/workflow_surface/expected_workflows.json",
    "scripts",
    "scripts/hooks",
    "scripts/godot_export.py",
    "scripts/godot_smoke.py",
    "scripts/hooks/pre_tool_use_policy.py",
    "scripts/hooks/session_start_context.py",
    "scripts/run_local_evals.py",
    "scripts/doc_sync_audit.py",
    "scripts/balance_simulator.py",
    "scripts/codex_studio.py",
    "scripts/ci_artifact_report.py",
    "scripts/validate_workflows.py",
    "scripts/starter_kit_contract_smoke.py",
    "scripts/studio_core.py",
    "scripts/unity_adapter.py",
    "scripts/unreal_adapter.py",
    "scripts/validate_engine_kits.py",
    "scripts/validate_agent_metadata.py",
    "scripts/seed_project_baseline.py",
    "scripts/toggle_codex_hooks.py",
    "scripts/start_game_studio.py",
    "scripts/scaffold_eval_plan.py",
    "studio/checklists",
    "studio/checklists/base",
    "studio/checklists/engine",
    "studio/checklists/discipline",
    "studio/checklists/milestone",
    "studio/checklists/custom",
    "studio/starter-kits",
    "studio/starter-kits/godot-4/kit.toml",
    "studio/starter-kits/unity-6/kit.toml",
    "studio/starter-kits/unreal-5/kit.toml",
    "studio/starter-kits/unity-6/scaffold/Assets/Scripts/Runtime/StarterKit.Runtime.asmdef",
    "studio/starter-kits/unity-6/scaffold/Assets/Scripts/Runtime/CombatRoomDirector.cs",
    "studio/starter-kits/unity-6/scaffold/Assets/Scripts/Runtime/EnemyArchetype.cs",
    "studio/starter-kits/unity-6/scaffold/Assets/Scripts/Runtime/Health.cs",
    "studio/starter-kits/unity-6/scaffold/Assets/Scripts/Runtime/PlayerAvatar.cs",
    "studio/starter-kits/unity-6/scaffold/Assets/Scripts/Runtime/PulseEnemy.cs",
    "studio/starter-kits/unity-6/scaffold/Assets/Scripts/Editor/BuildPipelineEntry.cs",
    "studio/starter-kits/unity-6/scaffold/Assets/Scripts/Editor/StarterKit.Editor.asmdef",
    "studio/starter-kits/unity-6/scaffold/Assets/Tests/EditMode/StarterKit.EditMode.asmdef",
    "studio/starter-kits/unity-6/scaffold/Assets/Tests/EditMode/CombatRoomDirectorTests.cs",
    "studio/starter-kits/unity-6/scaffold/Assets/Tests/EditMode/HealthTests.cs",
    "studio/starter-kits/unity-6/scaffold/Assets/Scenes/CombatRoom.unity",
    "studio/starter-kits/unity-6/scaffold/Assets/Prefabs/README.md",
    "studio/starter-kits/unity-6/scaffold/Assets/ScriptableObjects/README.md",
    "studio/starter-kits/unreal-5/scaffold/Config/DefaultEngine.ini",
    "studio/starter-kits/unreal-5/scaffold/Config/DefaultInput.ini",
    "studio/starter-kits/unreal-5/scaffold/Content/Blueprints/README.md",
    "studio/starter-kits/unreal-5/scaffold/Source/StarterKit/StarterKitCharacter.h",
    "studio/starter-kits/unreal-5/scaffold/Source/StarterKit/StarterKitCharacter.cpp",
    "studio/starter-kits/unreal-5/scaffold/Source/StarterKit/StarterKitEnemyActor.h",
    "studio/starter-kits/unreal-5/scaffold/Source/StarterKit/StarterKitEnemyActor.cpp",
    "studio/starter-kits/unreal-5/scaffold/Source/StarterKit/StarterKitGameModeBase.h",
    "studio/starter-kits/unreal-5/scaffold/Source/StarterKit/StarterKitGameModeBase.cpp",
    "studio/starter-kits/unreal-5/scaffold/Source/StarterKit/StarterKitEnemyArchetype.h",
    "studio/starter-kits/unreal-5/scaffold/Source/StarterKit/StarterKitHealthComponent.h",
    "studio/starter-kits/unreal-5/scaffold/Source/StarterKit/StarterKitHealthComponent.cpp",
    "studio/starter-kits/unreal-5/scaffold/Content/Maps/README.md",
    "studio/docs/templates",
    "studio/docs/templates/eval-plan.md",
    "studio/docs/templates/genre-starter.md",
    "studio/docs/templates/handoff-contract.md",
    "studio/docs/templates/feature-traceability.md",
    "docs/research/game-development",
    "docs/research/game-development/README.md",
    "studio/presets/genre/deckbuilder-roguelike.md",
    "studio/presets/genre/survivorlike.md",
    "studio/presets/genre/colony-sim.md",
    "studio/presets/genre/factory-automation.md",
    "studio/presets/genre/metroidvania.md",
    "studio/docs/active",
    "src",
    "tests",
    "tests/test_godot_surface.py",
    "tests/test_studio_system.py",
    "tests/test_ci_surface.py",
    "assets",
    "prototypes",
    "tools",
    "tools/engine-stubs",
    "tools/engine-stubs/README.md",
    "tools/engine-stubs/unity/Unity",
    "tools/engine-stubs/unreal/RunUAT.sh",
]

def main() -> int:
    missing = []
    for rel in REQUIRED_PATHS:
        path = REPO_ROOT / rel
        if not path.exists():
            missing.append(rel)
    if missing:
        for rel in missing:
            print(f"ERROR: Missing path: {rel}")
        return 1
    print("Repo layout validation passed.")
    return 0

if __name__ == "__main__":
    raise SystemExit(main())
