#!/usr/bin/env python3
from __future__ import annotations

from pathlib import Path

from _studio_common import REPO_ROOT

REQUIRED_PATHS = [
    "AGENTS.md",
    "README.md",
    "studio.toml",
    "CONTRIBUTING.md",
    "SECURITY.md",
    "SUPPORT.md",
    "CODE_OF_CONDUCT.md",
    ".env.example",
    "Makefile",
    ".github",
    ".github/CODEOWNERS",
    ".github/ISSUE_TEMPLATE",
    ".github/ISSUE_TEMPLATE/config.yml",
    ".github/ISSUE_TEMPLATE/bug-report.yml",
    ".github/ISSUE_TEMPLATE/feature-request.yml",
    ".github/ISSUE_TEMPLATE/infra-routing-change.yml",
    ".github/ISSUE_TEMPLATE/genre-preset-update.yml",
    ".github/pull_request_template.md",
    ".github/workflows",
    ".github/workflows/repo-validate.yml",
    ".github/workflows/docker-smoke.yml",
    ".github/dependabot.yml",
    "export_presets.cfg",
    ".codex/config.toml",
    ".codex/hooks.json",
    ".codex/agents",
    ".codex/agents/reviewer.toml",
    ".agents/skills",
    "docs/README.md",
    "docs/setup",
    "docs/setup/github-maintainer-setup.md",
    "docs/setup/optional-codex-hooks.md",
    "docs/setup/secrets-and-env.md",
    "docs/reference",
    "docs/reference/code-review.md",
    "docs/reference/codex-compatibility.md",
    "docs/reference/engine-agent-guidelines.md",
    "docs/reference/eval-strategy.md",
    "docs/reference/genre-presets.md",
    "docs/research",
    "docs/research/openai-codex-infra-findings.md",
    "docs/research/game-development/policy.md",
    "docs/research/game-development/templates/research-note.md",
    "docs/research/game-development/systems/gameplay-loop-state-and-update-architecture.md",
    "docs/research/game-development/systems/combat-damage-and-effects-architecture.md",
    "docs/research/game-development/systems/ai-navigation-and-entity-scale-architecture.md",
    "docs/research/game-development/systems/save-progression-and-runtime-data-architecture.md",
    "docs/research/game-development/genre/genre-design-pattern-catalog.md",
    "docs/research/game-development/genre/genre-example-matrix.md",
    "docs/research/game-development/engines/godot-4-2d-3d-navigation-damage-performance.md",
    "docs/research/game-development/engines/godot-4-class-editor-object-map.md",
    "docs/research/game-development/engines/unity-6-2d-3d-navigation-damage-performance.md",
    "docs/research/game-development/engines/unity-6-class-editor-object-map.md",
    "docs/research/game-development/engines/unreal-5-2d-3d-navigation-damage-performance.md",
    "docs/research/game-development/engines/unreal-5-class-editor-object-map.md",
    "evals",
    "evals/doctor_surface/required_checks.json",
    "evals/godot_surface/expectations.json",
    "evals/route_task/cases.json",
    "evals/genre_guidance/cases.json",
    "scripts",
    "scripts/hooks",
    "scripts/godot_export.py",
    "scripts/godot_smoke.py",
    "scripts/hooks/pre_tool_use_policy.py",
    "scripts/hooks/session_start_context.py",
    "scripts/run_local_evals.py",
    "scripts/codex_studio.py",
    "scripts/studio_core.py",
    "scripts/unity_adapter.py",
    "scripts/unreal_adapter.py",
    "scripts/validate_engine_kits.py",
    "scripts/seed_project_baseline.py",
    "scripts/toggle_codex_hooks.py",
    "scripts/start_game_studio.py",
    "scripts/scaffold_eval_plan.py",
    "studio/checklists",
    "studio/checklists/base",
    "studio/checklists/engine",
    "studio/checklists/discipline",
    "studio/checklists/milestone",
    "studio/checklists/custom",
    "studio/starter-kits",
    "studio/starter-kits/godot-4/kit.toml",
    "studio/starter-kits/unity-6/kit.toml",
    "studio/starter-kits/unreal-5/kit.toml",
    "studio/starter-kits/unity-6/scaffold/Assets/Scripts/Runtime/StarterKit.Runtime.asmdef",
    "studio/starter-kits/unity-6/scaffold/Assets/Scripts/Runtime/CombatRoomDirector.cs",
    "studio/starter-kits/unity-6/scaffold/Assets/Scripts/Runtime/EnemyArchetype.cs",
    "studio/starter-kits/unity-6/scaffold/Assets/Tests/EditMode/StarterKit.EditMode.asmdef",
    "studio/starter-kits/unity-6/scaffold/Assets/Tests/EditMode/CombatRoomDirectorTests.cs",
    "studio/starter-kits/unity-6/scaffold/Assets/Scenes/CombatRoom.unity",
    "studio/starter-kits/unreal-5/scaffold/Source/StarterKit/StarterKitGameModeBase.h",
    "studio/starter-kits/unreal-5/scaffold/Source/StarterKit/StarterKitGameModeBase.cpp",
    "studio/starter-kits/unreal-5/scaffold/Source/StarterKit/StarterKitEnemyArchetype.h",
    "studio/starter-kits/unreal-5/scaffold/Content/Maps/README.md",
    "studio/docs/templates",
    "studio/docs/templates/eval-plan.md",
    "studio/docs/templates/genre-starter.md",
    "docs/research/game-development",
    "docs/research/game-development/README.md",
    "studio/docs/active",
    "src",
    "tests",
    "tests/test_godot_surface.py",
    "tests/test_studio_system.py",
    "assets",
    "prototypes",
    "tools",
]

def main() -> int:
    missing = []
    for rel in REQUIRED_PATHS:
        path = REPO_ROOT / rel
        if not path.exists():
            missing.append(rel)
    if missing:
        for rel in missing:
            print(f"ERROR: Missing path: {rel}")
        return 1
    print("Repo layout validation passed.")
    return 0

if __name__ == "__main__":
    raise SystemExit(main())
